# https://coderwall.com/p/6zm8rq/how-to-create-a-lamp-stack-with-ansible

---
- name: 1. install Apache
  apt: name=apache2 state=present

- name: 2. install PHP module for Apache
  apt: name=php state=present

- name: 3. install PHP module for database
  apt: name=php-mysqli state=present

- name: 4. start Apache
  service: name=apache2 state=started enabled=yes

- name: 5. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664

- name: 6. remove index.html
  file: path=/var/www/html/index.html state=absent 